/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatPrivacyRouteImport } from './routes/cat/privacy'
import { Route as CatEthereumRouteImport } from './routes/cat/ethereum'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatPrivacyRoute = CatPrivacyRouteImport.update({
  id: '/cat/privacy',
  path: '/cat/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CatEthereumRoute = CatEthereumRouteImport.update({
  id: '/cat/ethereum',
  path: '/cat/ethereum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cat/ethereum': typeof CatEthereumRoute
  '/cat/privacy': typeof CatPrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cat/ethereum': typeof CatEthereumRoute
  '/cat/privacy': typeof CatPrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cat/ethereum': typeof CatEthereumRoute
  '/cat/privacy': typeof CatPrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cat/ethereum' | '/cat/privacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cat/ethereum' | '/cat/privacy'
  id: '__root__' | '/' | '/cat/ethereum' | '/cat/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatEthereumRoute: typeof CatEthereumRoute
  CatPrivacyRoute: typeof CatPrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cat/privacy': {
      id: '/cat/privacy'
      path: '/cat/privacy'
      fullPath: '/cat/privacy'
      preLoaderRoute: typeof CatPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cat/ethereum': {
      id: '/cat/ethereum'
      path: '/cat/ethereum'
      fullPath: '/cat/ethereum'
      preLoaderRoute: typeof CatEthereumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatEthereumRoute: CatEthereumRoute,
  CatPrivacyRoute: CatPrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
